name: Build & Release

# trigger on pushes to main
on:
  push:
    branches:
      - main

# grant the GITHUB_TOKEN rights to create releases & upload assets
permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyinstaller customtkinter pyserial

      - name: Build .exe with PyInstaller
        run: pyinstaller --onefile --windowed --name as511_tool --add-data "views;views" as511_gui.py

      - name: Compute release tag
        id: compute_tag
        shell: bash
        run: |
          # e.g. 2025-05-10_15-42
          TAG=$(date +'%Y-%m-%d_%H-%M')
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Compress EXE into ZIP
        shell: bash
        run: |
          zip="${TAG}.zip"
          zip -j "$zip" dist/as511_tool.exe
          echo "ZIP=$zip" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.TAG }}
          release_name: ${{ env.TAG }}
          body: "Automated build for ${{ env.TAG }}"
          draft: false
          prerelease: false

      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ZIP }}
          asset_name: ${{ env.ZIP }}
          asset_content_type: application/zip
