name: Build & Release

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyinstaller customtkinter pyserial

      - name: Build .exe with PyInstaller
        run: pyinstaller --onefile --windowed --name as511_tool --add-data "views;views" as511_gui.py

      - name: Compute release tag
        shell: pwsh
        run: |
          # e.g. "2025-05-09_14-27"
          $tag = Get-Date -Format 'yyyy-MM-dd_HH-mm'
          echo "TAG=$tag" >> $env:GITHUB_ENV

      - name: Compress EXE into ZIP
        shell: pwsh
        run: |
          $zip = "${{ env.TAG }}.zip"
          Compress-Archive -Path dist\as511_tool.exe -DestinationPath $zip -Force

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.TAG }}
          release_name: ${{ env.TAG }}
          body: "Automated build for ${{ env.TAG }}"
          draft: false
          prerelease: false

      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "${{ env.TAG }}.zip"
          asset_name: "${{ env.TAG }}.zip"
          asset_content_type: application/zip
