# .github/workflows/build-and-release.yml
name: Build & Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  # allow GITHUB_TOKEN to create releases & upload assets

jobs:
  build_and_release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyinstaller customtkinter pyserial

      - name: Build .exe with PyInstaller
        run: pyinstaller --onefile --windowed --name as511_tool --add-data "views;views" as511_gui.py

      - name: Compute release tag
        shell: pwsh
        run: |
          $tag = (Get-Date).ToString('yyyy-MM-dd_HH-mm')
          Add-Content -Path $Env:GITHUB_ENV -Value "TAG=$tag"

      - name: Compress EXE into ZIP
        shell: pwsh
        run: |
          $zip = "$Env:TAG.zip"
          Compress-Archive -Path "dist\as511_tool.exe" -DestinationPath $zip -Force
          Add-Content -Path $Env:GITHUB_ENV -Value "ZIP=$zip"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.TAG }}
          release_name: ${{ env.TAG }}
          body: "Automated build for ${{ env.TAG }}"
          draft: false
          prerelease: false

      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ZIP }}
          asset_name: ${{ env.ZIP }}
          asset_content_type: application/zip
